name: Deploy SAM App

on:
  workflow_dispatch:
    inputs:
      caller-repo:
        required: true
        type: string
      stack-name:
        required: true
        type: string
      s3-bucket:
        required: true
        type: string
      region:
        required: true
        type: string
      template:
        required: true
        type: string
      parameters:
        required: false
        type: string

permissions:
  contents: write
  id-token: write
  pull-requests: write

env:
  PROJECT_PATH: ${{ github.workspace }}/project  # For checking out repo into specific dir

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.caller-repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.PROJECT_PATH }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Validate SAM template
        run: sam validate --template-file $PROJECT_PATH/${{ inputs.template }}

      - name: Build SAM app
        run: sam build --template $PROJECT_PATH/${{ inputs.template }}

      - name: Package SAM app
        run: |
          sam package \
            --s3-bucket ${{ inputs.s3-bucket }} \
            --output-template-file packaged.yaml

      - name: Deploy SAM app
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name ${{ inputs.stack-name }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ inputs.region }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            ${{ inputs.parameters }}
