name: Deploy via Shared CD Workflow
  
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  trigger-shared-deploy:
    uses: blee1077/github-workflows/.github/workflows/trigger-deploy-aws-sam.yaml@main
    with:
      stack-name: example-app-name
      s3-bucket: aws-sam-cli-managed-default-samclisourcebucket
      region: eu-west-2
      parameters: --parameter-overrides \
        DingDong=dingdong \
        PingPong=pingpong \
        foo=bar
    secrets: inherit