name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      caller-repo:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string
      image-name:
        required: true
        type: string
      image-tag:
        required: false
        type: string
        default: latest
      run-trivy-scan-and-copa-patch:
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout calling project repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.caller-repo }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.16.0
        with:
          context: ${{ inputs.dockerfile-path }}
          file: ${{ inputs.dockerfile-path }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}:${{ inputs.image-tag }}

      - name: Scan image for vulnerabilities with Trivy
        if: ${{ inputs.run-trivy-scan-and-copa-patch }}
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
          format: json
          output: trivy-report.json
          ignore-unfixed: true

      - name: Upload Trivy Scan Report
        if: ${{ inputs.run-trivy-scan-and-copa-patch }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
          retention-days: 7

      - name: Check High/Criticial Vulnerabilities
        if: ${{ inputs.run-trivy-scan-and-copa-patch }}
        env:
          TRIVY_FORMAT: table
          TRIVY_OUTPUT:
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: false
          # Don't fail workflow when high/critical vulns are present
          exit-code: 0
          # On a subsequent call to the action we know trivy is already installed so can skip this
          skip-setup-trivy: true

      - name: Patch image with Copa
        if: ${{ inputs.run-trivy-scan-and-copa-patch }}
        run: |
          VERSION=$(curl -s https://api.github.com/repos/project-copacetic/copacetic/releases/latest | jq -r .tag_name)
          FILE="copa_${VERSION#v}_linux_amd64.tar.gz"
          URL="https://github.com/project-copacetic/copacetic/releases/download/${VERSION}/${FILE}"

          # Download Copa, extract, and 'install'
          curl -sSL "$URL" -o copa.tar.gz
          tar -xzf copa.tar.gz
          sudo mv copa /usr/local/bin/
          copa --version

          image=${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}
          tag=${{ inputs.image-tag }}

          # Patch and overwrite the original image
          copa patch -i $image:$tag -r trivy-report.json -t -t $image:$tag

          docker push $image:$tag
