name: Trigger Shared SAM Deploy

on:
  workflow_call:
    inputs:
      stack-name:
        required: true
        type: string
      s3-bucket:
        required: true
        type: string
      region:
        required: true
        type: string
      template:
        required: false
        type: string
        default: template.yaml
      parameters:
        required: false
        type: string
        default: ''

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-aws-sam.yaml
    with:
      stack-name: ${{ inputs.stack-name }}
      s3-bucket: ${{ inputs.s3-bucket }}
      region: ${{ inputs.region }}
      template: ${{ inputs.template }}
      parameters: ${{ inputs.parameters }}
