# .github/workflows/deploy.yml (in project repo)

name: Trigger Shared SAM Deploy

on:
  workflow_call:
    inputs:
      stack_name:
        required: true
        default: sweater-discount-app
      s3_bucket:
        required: true
        default: your-s3-bucket
      region:
        required: true
        default: eu-west-2
      template:
        required: false
        default: template.yaml
      parameters:
        required: false
        default: ""

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger shared repo deploy via API
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: |
          curl -X POST https://api.github.com/repos/blee1077/github-workflows/actions/workflows/deploy-aws-sam.yaml/dispatches \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d '{
              "ref": "main",
              "inputs": {
                "stack_name": "${{ inputs.stack_name }}",
                "s3_bucket": "${{ inputs.s3_bucket }}",
                "region": "${{ inputs.region }}",
                "template": "${{ inputs.template }}",
                "parameters": "${{ inputs.parameters }}"
              }
            }'
